image: ruby:2.3.1

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc) "${FLAGS[@]}"
  - cd config
  - echo domain: "example.com" > application.yml

rspec:
  script:
    - bundle exec rspec
